[package]
name = "fenxing"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Guangxi Liu <https://github.com/liuguangxi>"]
license = "MIT"
description = "Create a variety of wonderful fractals in Typst."
repository = "https://github.com/liuguangxi/fenxing"
keywords = ["fractal", "L-system", "dragon", "Hilbert", "Koch"]
categories = ["components", "visualization"]
disciplines = ["computer-science", "mathematics"]
compiler = "0.11.0"
exclude = ["examples", "tests"]
